import type { Metadata } from "next";
import Script from 'next/script';
import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/assets/css/pokemon.css";
import "../../public/assets/css/pixels.css";

import Header from '@/components/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Optimizely CMS Boilerplate - Create Next App",
  description: "Generated by create next app for Optimizely CMS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="/assets/css/main.css"/>
      <Script type="module" src="/assets/js/vendor.mjs" strategy="lazyOnload"></Script>
      <Script type="module" src="/assets/js/main.mjs" strategy="lazyOnload"></Script>
    </head>
    <body className={inter.className}>
    <Header/>
    <main>
      {children}
    </main>
    </body>
    </html>
  );
}
