import type {Metadata} from "next";
import Script from 'next/script';
import {Inter} from "next/font/google";
import "./../globals.css";
import "../../../public/assets/css/pokemon.css";
import Spin from "../../components/spin/Spin"

import { Sause } from "./../search/components/sause";

const inter = Inter({subsets: ["latin"]});
export const metadata: Metadata = {
    title: "Optimizely CMS Boilerplate - Create Next App",
    description: "Generated by create next app for Optimizely CMS",
};

export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <Script type="module" src="/assets/js/vendor.mjs" strategy="lazyOnload"></Script>
                <Script type="module" src="/assets/js/main.mjs" strategy="lazyOnload"></Script>
            </head>
            <body className={inter.className}>
                <Spin />
                <main className="medium">
                    <Sause useplane={false} />

                    {children}
                </main>
            </body>
        </html>
    );
}
